name: "Dev Deploy"

on:
    push:
        branches:
            - develop

# required for assume role
permissions:
    id-token: write
    contents: read

jobs:
    terraform:
        uses: ./.github/workflows/terraform.yml
        with:
            environment: dev
            aws-assume_role_arn: "arn:aws:iam::019233110154:role/github-action-marcelobracet-pipeline"
            aws-statefile-s3-bucket: "marcelobracet-es-east-1-terraform-state-file"
            aws-lock-dynamodb-table: "marcelobracet-es-east1-terraform-lock"
            aws-region: us-east-2
